version: "3.1"
services:
  db:
    image: postgres:15.1-alpine
    container_name: trading-db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: "${DB_USER_ID}"
      POSTGRES_PASSWORD: "${DB_USER_PASSWORD}"
    volumes:
      - ./data:/var/lib/postgresql/data
volumes:
  data: