version: '3.1'
services:
  mongo:
    image: mongo
    container_name: '${CONTAINER_NAME}'
    ports:
      - '${OUT_PORT}:${IN_PORT}'
    restart: always
    volumes:
      - ./data:/data/db
volumes:
  data:
